export const access_token_secret =
  'eyJzdWIiOiIzNzJmZTJiYS0yNDM5LTQwMmMtYTczZS0yYjNhYTBhODkyNTUiLCJpYXQiOjE2NTUzNzM1NDAsImV4cCI6MT';
export const refresh_token_secret =
  'bImFkbWluIiwidXNlciIsImRldmVsb3BlciIsIm1hbmFnZXIiLCJ0ZXN0ZXIiXSwieC1oYXN1cmEtZW1haWwiOiJBcmthbU';
