# Use postgres/example user/password credentials
version: '3.1'

services:

  authdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: arkam
      POSTGRES_PASSWORD: Arkam2004
      POSTGRES_DB: AuthDb
    ports:
      - 5431:5432
